<?php

namespace App\Http\Constants;


class ResponseCodeConstant
{
    const CONSTANT_RESPONSE_CODE_SUCCESS = 100000;//成功
    const CONSTANT_RESPONSE_CODE_FAILED = 200000;//失败
    const CONSTANT_RESPONSE_CODE_AUTH_NOT_ALLOW = 200001;//未被授权访问这套接口
    const CONSTANT_RESPONSE_CODE_PARAM_ILLEGAL = 200003;//参数不合法，必填的参数没有传入，或类型不合法
    const CONSTANT_RESPONSE_CODE_METHOD_NOT_ALLOW = 200003;//HTTP 请求方式非法
    const CONSTANT_RESPONSE_CODE_DENIAL_OF_SERVICE = 200004;//请求频率超出限制，拒绝服务
    const CONSTANT_RESPONSE_CODE_API_CLOSED = 200005;//API 接口维护中
    const CONSTANT_RESPONSE_CODE_NOT_FUND_RESOURCE = 200006;//请求的资源不存在（资源 404）
    const CONSTANT_RESPONSE_CODE_AUTH_API_LIMITED = 200007;//用户权限不足以使用该接口能力
    const CONSTANT_RESPONSE_CODE_AUTH_RESOURCE_LIMITED = 200008;//用户权限不足以访问该资源
    const CONSTANT_RESPONSE_CODE_REMOTE_SERVICE_NOT_AVAILABLE = 200009;//接口能力需要的远程服务不可用
    const CONSTANT_RESPONSE_CODE_UPLOAD_ILLEGAL = 200010;//上传的文件不符合类型或大小限定
    const CONSTANT_RESPONSE_CODE_HTTPS_NECESSARY = 200011;//必须使用 HTTPS 访问
    const CONSTANT_RESPONSE_CODE_RESOLVE_JSON_XML_ERROR = 200012;//解析 JSON/XML 内容错误
    const CONSTANT_RESPONSE_CODE_LOGIN_STATUS_OVER_TIME = 200013;//登录状态超时,重新登录
    const CONSTANT_RESPONSE_CODE_CACHE_NOT_EXIST = 200014;//缓存不存在
    const CONSTANT_RESPONSE_CODE_CACHE_ERROR = 200015;//缓存错误
    const CONSTANT_RESPONSE_CODE_USER_EMAIL_EXIST = 200016;//用户email已存在
    const CONSTANT_RESPONSE_CODE_USER_EMAIL_OR_PASSWORD_ERROR = 200017;//用户email或password错误
    const CONSTANT_RESPONSE_CODE_USER_NOT_EXIST = 200018;//用户不存在
    const CONSTANT_RESPONSE_CODE_OBJECT_NOT_EXIST = 200019;//对象不存在
    const CONSTANT_RESPONSE_CODE_ROLE_SUPER = 200020;//超级管理员
    const CONSTANT_RESPONSE_CODE_NAME_EXIST = 200021;//名字已存在
    const CONSTANT_RESPONSE_CODE_OBJECT_HAS_CHILDREN = 200022;//对象下有子对象
}
